spring:
    application:
        name: api-sync
    config:
        activate:
            on-profile: test
    docker:
        compose:
            enabled: false
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/datossqlweb
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
name: test
environment: testing
enabled: false


---
spring:
    config:
        activate:
            on-profile: prod
    docker:
        compose:
            enabled: false
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
        username: ${MYSQLUSER}
        password: ${MYSQLPASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    name: prod
    environment: production
    enabled: true


